name: Bug report
description: Report a bug
body:
  - type: dropdown
    id: install
    attributes:
      label: "Installation type"
      options:
        - Flatpak (.flatpak)
        - Source
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: "Version"
      placeholder: 1.0.0
    validations:
      required: true

  - type: input
    id: platform
    attributes:
      label: "Platform"
      placeholder: Fedora 42
    validations:
      required: true

  - type: input
    id: desktop
    attributes:
      label: "Desktop Environment"
      placeholder: GNOME, KDE, ...

  - type: input
    id: windowing
    attributes:
      label: "Windowing System"
      placeholder: Wayland, X11, ...

  - type: input
    id: gpu
    attributes:
      label: "GPU"
      placeholder: AMD
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "Describe the bug"
      placeholder: "Please do not use AI/LLMs to generate the description, it makes it hard to understand the actual issue"
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: "Logs"
